### ISSUE TITLE
1.3.2 : crash on load

### ISSUE THREAD

**Issue by steren** [kelektiv/node-uuid#37]
I'm using node v0.4.11

Everything works with node-uuid 1.3.0

But when I used node-uuid 1.3.2, on launch of my app : 

node.js:134

```
    throw e; // process.nextTick error, or 'error' event on first tick

    ^
```

TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /xxx/node_modules/node-uuid/uuid.js:47:14
    at /xxx/node_modules/node-uuid/uuid.js:103:20
    at Object.<anonymous> (/xxx/node_modules/node-uuid/uuid.js:249:1)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/xxx/server/lib/server.js:16:12)
